development:
  adapter: postgresql
  encoding: utf-8
  database: abantos_dev
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf-8
  database: abantos_test
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000

production:
 adapter: postgresql
 encoding: utf-8
 database: abantos_prod
 host: localhost
 username: postgres
 password: postgres
 pool: 5
 timeout: 5000